version: '3.3'

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  wordpress:
    container_name: ${CONTAINER_NAME}
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${HTTP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./data/wordpress:/var/www/html
      - ./themes/dist:/var/www/html/wp-content/themes/webdev-theme

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db

volumes:
  wordpress:
  db:
